                                                                                                                                                                                                                                                                                   
import java.io.Serializable;                                                                                                                                                                                                                                                       
import java.util.ArrayList;                                                                                                                                                                                                                                                        
import java.util.StringTokenizer;                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                   
public class Student implements Serializable{                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                   
	private static final long serialVersionUID = 1L;                                                                                                                                                                                                                               
	                                                                                                                                                                                                                                                                               
	protected String studentId;                                                                                                                                                                                                                                                    
    protected String lName;                                                                                                                                                                                                                                                        
    protected String fName;                                                                                                                                                                                                                                                        
    protected String department;                                                                                                                                                                                                                                                   
    protected ArrayList<String> completedCoursesList;                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
    public Student(String inputString) {                                                                                                                                                                                                                                           
        StringTokenizer stringTokenizer = new StringTokenizer(inputString);                                                                                                                                                                                                        
    	this.studentId = stringTokenizer.nextToken();                                                                                                                                                                                                                             
    	this.lName = stringTokenizer.nextToken();                                                                                                                                                                                                                                  
    	this.fName = stringTokenizer.nextToken();                                                                                                                                                                                                                              
    	this.department = stringTokenizer.nextToken();                                                                                                                                                                                                                               
    	this.completedCoursesList = new ArrayList<String>();                                                                                                                                                                                                                       
    	while (stringTokenizer.hasMoreTokens()) {                                                                                                                                                                                                                                  
    		this.completedCoursesList.add(stringTokenizer.nextToken());                                                                                                                                                                                                            
    	}                                                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
    public boolean match(String studentId) {                                                                                                                                                                                                                                       
        return this.studentId.equals(studentId);                                                                                                                                                                                                                                   
    }                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
    public String getName() {                                                                                                                                                                                                                                                      
    	if(fName.length()<8) {                                                                                                                                                                                                                                                     
            return this.lName+"\t"+this.fName+"\t";                                                                                                                                                                                                                                                 
    	}else {
            return this.lName+"\t"+this.fName;       
    	}                                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
    public ArrayList<String> getCompletedCourses() {                                                                                                                                                                                                                               
        return this.completedCoursesList;                                                                                                                                                                                                                                          
    }                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
    public String toString() {                                                                                                                                                                                                                                                     
        String stringReturn = this.studentId + "\t" + getName() + "\t" + this.department;                                                                                                                                                                                          
        for (int i = 0; i < this.completedCoursesList.size(); i++) {                                                                                                                                                                                                               
            stringReturn = stringReturn + "\t" + this.completedCoursesList.get(i).toString();                                                                                                                                                                                      
        }                                                                                                                                                                                                                                                                          
        return stringReturn;                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                   
}                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                   